### ISSUE TITLE
oauth2cer.jks

### ISSUE THREAD

**Issue by Olivier4477** [rshtishi/payroll#3]
Hi,

I finally have a little time to resume my microservice project.

I still haven't managed to secure my architecture.
I still don't know what to use! (jwt, oauth2, ...)

I am looking for something simple and reliable and if possible easy to implement

I am in web flow with gateway etc ...
What is this oauth2cer.jks file?

thank you

**Comment by rshtishi** [comment]
Hello,

In the microservice architecture, you have multiple standalone applications that need to be secured.  Implementing securing mechanism for each service is not feasible. We need to centralize the authentication mechanism into an authorization server that will authenticate and secure all our services.  

### OAuth2

OAuth2  is the industry-standard protocol for authorization. How it works:

- Resource Owner (Me, you who has owns the data)
- Client (The angular app that is trying to access the data)
- Authorization Server( Has resource owner information(username, password) and it responsible for authorizing the angular application to access the information on service by issue token )
-  Token that is issued by the authorization server  contains user information and also the grant that defines what is the level of access of the client to the service.

When the client is authenticated successfully , obtains a token that permits accessing the information from all services secured from the authorization server. The level of access is specified by the grants information stored in the token.

### JWT 

JWT is used for authentication and exchanging information:

- With the JWT token the server doesn't need to store information about the client. The server creates json web token and signed with his private key.  In this way the server is able te identify if token is modified.
- In the json web token payload you can add the information you wish to share with the application like the username, roles and etc.

### oauth2cer.jks

oauth2cer.jks is the file that store the private and public key. I use the private key to sign the token  and send it to the user. And verify with the public key if the web token is modified by the user.

**Comment by rshtishi** [comment]
For implementation details you can check the link:  https://github.com/rshtishi/payroll/tree/master/oauth2-server
